### ISSUE TITLE
Project Search Is Broken

### ISSUE THREAD

**Issue by RunTheCoins** [scratchbackup/scratchbackup.github.io#86] opened 2022-02-01 02:09 UTC
whenever I search for a project, it does absolutely nothing...
I was hoping to use this to restore a few builds of a fan project me and a couple of friends worked on, as you could in the instructions, search by name...
![Screen Shot 2022-01-31 at 9 05 21 PM](https://user-images.githubusercontent.com/81893577/151902927-9a8a1e03-7623-4e12-9998-cda273d3aa9d.png)
![Screen Shot 2022-01-31 at 9 04 26 PM](https://user-images.githubusercontent.com/81893577/151902934-18ba29b9-a0a3-4bad-a28b-8a87e0d996ff.png)

So since I know this build could be named differently as It was never shared, I decided to check to see if search even worked with you know... Any Project.
Sadly at the moment, there is a bug it looks like that disables you to search.
But, thank you for editing the code at least so the webpage loads!

**Comment by ScolderCreations** [comment] 2022-02-01 16:51
duplicate of #83, because it’s the same problem

**Closed by ScolderCreations** 2022-02-01 16:51 UTC
